1: 01-comp_DD_ang.o catalogue.o functions.o
	g++ 01-comp_DD_ang.o catalogue.o functions.o -o 01-comp_DD_ang.exe -lm -fopenmp
01-comp_DD_ang.o: 01-comp_DD_ang.cpp
	g++ -c 01-comp_DD_ang.cpp -lm -fopenmp


2: 02-comp_DR_ang.o catalogue.o functions.o
	g++ 02-comp_DR_ang.o catalogue.o functions.o -o 02-comp_DR_ang.exe -lm -fopenmp
02-comp_DR_ang.o: 02-comp_DR_ang.cpp
	g++ -c 02-comp_DR_ang.cpp -lm -fopenmp


3: 03-norm_count_DD_ang.o catalogue.o functions.o
	g++ 03-norm_count_DD_ang.o catalogue.o functions.o -o 03-norm_count_DD_ang.exe -lm -fopenmp
03-norm_count_DD_ang.o: 03-norm_count_DD_ang.cpp
	g++ -c 03-norm_count_DD_ang.cpp -lm -fopenmp


4: 04-norm_count_DR_ang.o catalogue.o functions.o
	g++ 04-norm_count_DR_ang.o catalogue.o functions.o -o 04-norm_count_DR_ang.exe -lm -fopenmp
04-norm_count_DR_ang.o: 04-norm_count_DR_ang.cpp
	g++ -c 04-norm_count_DR_ang.cpp -lm -fopenmp


5: 05-comp_DD_mps_pip.o catalogue.o functions.o
	g++ 05-comp_DD_mps_pip.o catalogue.o functions.o -o 05-comp_DD_mps_pip.exe -lm -fopenmp
05-comp_DD_mps_pip.o: 05-comp_DD_mps_pip.cpp
	g++ -c 05-comp_DD_mps_pip.cpp -lm -fopenmp


6: 06-comp_DR_mps_pip.o catalogue.o functions.o
	g++ 06-comp_DR_mps_pip.o catalogue.o functions.o -o 06-comp_DR_mps_pip.exe -lm -fopenmp
06-comp_DR_mps_pip.o: 06-comp_DR_mps_pip.cpp
	g++ -c 06-comp_DR_mps_pip.cpp -lm -fopenmp


7: 07-comp_RR_mps.o catalogue.o functions.o
	g++ 07-comp_RR_mps.o catalogue.o functions.o -o 07-comp_RR_mps.exe -lm -fopenmp
07-comp_RR_mps.o: 07-comp_RR_mps.cpp
	g++ -c 07-comp_RR_mps.cpp -lm -fopenmp


8: 08-comp_DD_wp_pip.o catalogue.o functions.o
	g++ 08-comp_DD_wp_pip.o catalogue.o functions.o -o 08-comp_DD_wp_pip.exe -lm -fopenmp
08-comp_DD_wp_pip.o: 08-comp_DD_wp_pip.cpp
	g++ -c 08-comp_DD_wp_pip.cpp -lm -fopenmp


9: 09-comp_DR_wp_pip.o catalogue.o functions.o
	g++ 09-comp_DR_wp_pip.o catalogue.o functions.o -o 09-comp_DR_wp_pip.exe -lm -fopenmp
09-comp_DR_wp_pip.o: 09-comp_DR_wp_pip.cpp
	g++ -c 09-comp_DR_wp_pip.cpp -lm -fopenmp


10: 10-comp_RR_wp.o catalogue.o functions.o
	g++ 10-comp_RR_wp.o catalogue.o functions.o -o 10-comp_RR_wp.exe -lm -fopenmp
10-comp_RR_wp.o: 10-comp_RR_wp.cpp
	g++ -c 10-comp_RR_wp.cpp -lm -fopenmp


11: 11-norm_count_DD_pip.o catalogue.o functions.o
	g++ 11-norm_count_DD_pip.o catalogue.o functions.o -o 11-norm_count_DD_pip.exe -lm -fopenmp
11-norm_count_DD_pip.o: 11-norm_count_DD_pip.cpp
	g++ -c 11-norm_count_DD_pip.cpp -lm -fopenmp


12: 12-norm_count_DR_pip.o catalogue.o functions.o
	g++ 12-norm_count_DR_pip.o catalogue.o functions.o -o 12-norm_count_DR_pip.exe -lm -fopenmp
12-norm_count_DR_pip.o: 12-norm_count_DR_pip.cpp
	g++ -c 12-norm_count_DR_pip.cpp -lm -fopenmp


13: 13-norm_count_RR_pip.o catalogue.o functions.o
	g++ 13-norm_count_RR_pip.o catalogue.o functions.o -o 13-norm_count_RR_pip.exe -lm -fopenmp
13-norm_count_RR_pip.o: 13-norm_count_RR_pip.cpp
	g++ -c 13-norm_count_RR_pip.cpp -lm -fopenmp


14: 14-norm_count_DD_pip_cross.o catalogue.o functions.o
	g++ 14-norm_count_DD_pip_cross.o catalogue.o functions.o -o 14-norm_count_DD_pip_cross.exe -lm -fopenmp
14-norm_count_DD_pip_cross.o: 14-norm_count_DD_pip_cross.cpp
	g++ -c 14-norm_count_DD_pip_cross.cpp -lm -fopenmp


catalogue.o: classes/catalogue.cpp
	g++ -c classes/catalogue.cpp -Wall -Werror -lm
functions.o: classes/functions.cpp
	g++ -c classes/functions.cpp -Wall -Werror -lm
